### ISSUE TITLE
Code Issues with Mario & Luigi: Superstar Saga + Bowser's Minions (US)

### ISSUE THREAD

**Issue by JustPlayJared** [BernardoGiordano/Sharkive#10] opened 2018-01-14 15:36 UTC
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 001B8F00
* **Product code**: CTR-P-BRME
* **Game version**: 1.0

### Red codes

* 00BBA6CD 00000063
* Multiple codes appear in their hex formatting like this, though this is the only invalid one.

**Comment by ValliantStorme** [comment] 2018-03-22 05:16
Luma doesn't have support for code descriptions 
`{in the brackets}`
or collapsable groups/categories
`[--] [++]`
yet; I think that might be the issue

**Comment by JourneyOver** [comment] 2018-03-22 05:30
@ValliantStorme yes that is true, and it more than likely never will. I plan on going through the DB here soonish and rework how some txt files are setup as right now everything that is in the DB is mainly just a reflection of my own AR/Gateshark database so there are a lot of things that need to be changed/removed still on this side of things.

**Comment by JourneyOver** [comment] 2018-03-22 06:15
@ValliantStorme Hmm that is very strange, as my editor I use deletes whitespaces that are not needed..but I can confirm that they are there when looking at the source. I'll fix it up here soon. Thanks for finding that as I'd probably of never of noticed it.

**Comment by BernardoGiordano** [comment] 2018-03-25 12:54
Closing because this needs to be re-checked due to latest Luma changes.

**Closed by BernardoGiordano** 2018-03-25 12:54 UTC
